runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /
  script: index.html

- url: /(.+\.(ico|jpg|png|gif|mp3))$
  static_files: \1
  upload: (.+\.(ico|jpg|png|gif|mp3))$
  application_readable: true

- url: /(.+\.(htm|html|css|js))$
  static_files: \1
  upload: (.+\.(htm|html|css|js))$
  application_readable: true

- url: /(.+\.php)$
  script: \1
